os:
- linux
- osx
language: c
sudo: required
services:
- docker
script: bash scripts/travis-setup.sh; bash scripts/travis-run.sh
env:
  global:
  - ENCRYPTION_LABEL: "33e9f3ccc52a"
  - COMMIT_AUTHOR_EMAIL: "jillian.e.rowe@gmail.com"
