name: gencore_rnaseq
channels:
  - bioconda
dependencies:
  - samtools=1.3.1
  - bcftools=1.3.1
  - kallisto=0.43.0
  - blat=35
  - gatk=3.6
  - picard=2.5.0
  - prinseq=0.20.4
  - kallisto=0.6.0
  - star=2.5.2a
  - vcftools=0.1.14
  - bedtools=2.25.0
  - vcflib-1.0.0_rc1
  - bamtools=2.4.0
