name: gencore_epigenetics_1.0
channels:
  - bioconda
dependencies:
  - samtools=1.3.1
  - bcftools=1.3.1
  - bedtools=2.25.0
  - vcftools=0.1.14
  - bwa=0.7.15
  - bamtools=2.4.0
  - vcflib=1.0.0_rc1
  - bowtie2=2.2.8
  - numpy=1.11.1
  - python=2.7
  - pip:
    - macs2
