name: gencore_qc_1.0
channels:
  - bioconda
dependencies:
  - perl-hpc-runner-slurm=2.58
  - perl-biox-workflow=1.10
  - perl-biox-workflow-plugin-fileexists=0.13
  - trimmomatic=0.36
  - fastqc=0.11.5
